### ISSUE TITLE
[Feature]: Use system default editor to edit manifest file

### ISSUE THREAD

**Issue by gili-gili** [microsoft/win32-app-isolation#28]
### Summary

Unable to edit manifest if you have Notepad uninstalled, even if a editor is specified as the default application to edit `.manifest` files.
It's also a problem for those who want use other editors for more features (e.g syntax highlighing, auto-completion).

## Screenshot
![Screenshot 2023-05-26 050147](https://github.com/microsoft/win32-app-isolation/assets/53759426/9cfef65a-520d-4a04-aa0c-178fb9fb64b4)

## Log
```
[5/26/2023 4:55:59] [Warning] Error occurred while working on the manifest file. System.ComponentModel.RunWorkerCompletedEventArgs
[5/26/2023 4:55:59] [Warning] Error Occurred: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at MsixPackagingTool.ViewModel.PackageEditorWorkflow.PackageInformationViewModel.OpenManifestFileProcess(InstallerHelper installerHelper)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by lilybarkley-msft** [comment]
Thanks for reporting this issue, we'll get this feature request over to our partners in the MPT team.
